apiVersion: skaffold/v2beta22
kind: Config
build:
  artifacts:
  - image: discovery-service
    jib:
      project: discovery-service
  - image: gateway-service
    jib:
      project: gateway-service
  - image: configuration-service
    jib:
      project: configuration-service
  - image: configuration-sidecar
    jib:
      project: configuration-sidecar
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
    - ./kubernetes-manifests/**/**.yaml
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
- name: dockerfile
  build:
    artifacts:
    - image: discovery-service
      context: discovery-service
    - image: gateway-service
      context: gateway-service
    - image: configuration-service
      context: configuration-service
    - image: config-client-java
      context: config-client-java
