apiVersion: v1
kind: Service
metadata:
  name: configuration-service
  namespace: spring-cloud-config
  labels:
    app: configuration-service
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: configuration-service
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
