apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: spring-cloud-config
  labels:
    app: ui
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
      tier: backend
  template:
    metadata:
      labels:
        app: ui
        tier: backend
    spec:
      containers:
        - name: ui
          image: ui
          ports:
            - name: http-server
              containerPort: 8080
          env:
            - name: HOST_NAME
              value: ui
            - name: eureka.client.service-url.defaultZone
              value: http://discovery-service:8761/eureka
