logging:
  level:
    root: INFO
    org:
      apache:
        http: INFO
    springframework:
      data:
        rest:
          webmvc:
            json: INFO
management:
  health:
    gateway:
      enabled: true
    vault:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          filters:
            - RewritePath='/' + serviceId + '/(?<remaining>.*)', '/${remaining}'
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
  main:
    allow-bean-definition-overriding: true
  devtools:
    add-properties: true
