instance:
  name: instance01
logging:
  level:
    root: ERROR
    uk:
      co:
        jamesmcguigan:
          spring:
            cloud:
              configuration:
                sidecar: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
prop1: prop1 from local
server:
  port: 8080
