apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-sidecar
  namespace: spring-cloud-config
  labels:
    app: configuration-sidecar
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configuration-sidecar
      tier: backend
  template:
    metadata:
      labels:
        app: configuration-sidecar
        tier: backend
    spec:
      containers:
      - name: configuration-sidecar
        image: configuration-sidecar
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: HOST_NAME
          value: configuration-sidecar
        - name: eureka.client.service-url.defaultZone
          value: http://discovery-service:8761/eureka
      - name: configuration-consumer
        image: configuration-consumer
        env:
          - name: HOST_NAME
            value: configuration-consumer
